// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk-service.proto

package net.csonic.grpc.server;

/**
 * Protobuf type {@code EvaluationResponse}
 */
public final class EvaluationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EvaluationResponse)
    EvaluationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EvaluationResponse.newBuilder() to construct.
  private EvaluationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EvaluationResponse() {
    id_ = "";
    customerId_ = "";
    moodys_ = "";
    pcr_ = "";
    sbs_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new EvaluationResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RiskServiceOuterClass.internal_static_EvaluationResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RiskServiceOuterClass.internal_static_EvaluationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            EvaluationResponse.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @Override
  public String getId() {
    Object ref = id_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    Object ref = id_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object customerId_ = "";
  /**
   * <code>string customer_id = 2;</code>
   * @return The customerId.
   */
  @Override
  public String getCustomerId() {
    Object ref = customerId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      customerId_ = s;
      return s;
    }
  }
  /**
   * <code>string customer_id = 2;</code>
   * @return The bytes for customerId.
   */
  @Override
  public com.google.protobuf.ByteString
      getCustomerIdBytes() {
    Object ref = customerId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      customerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MOODYS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object moodys_ = "";
  /**
   * <code>string moodys = 3;</code>
   * @return The moodys.
   */
  @Override
  public String getMoodys() {
    Object ref = moodys_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      moodys_ = s;
      return s;
    }
  }
  /**
   * <code>string moodys = 3;</code>
   * @return The bytes for moodys.
   */
  @Override
  public com.google.protobuf.ByteString
      getMoodysBytes() {
    Object ref = moodys_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      moodys_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PCR_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object pcr_ = "";
  /**
   * <code>string pcr = 4;</code>
   * @return The pcr.
   */
  @Override
  public String getPcr() {
    Object ref = pcr_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      pcr_ = s;
      return s;
    }
  }
  /**
   * <code>string pcr = 4;</code>
   * @return The bytes for pcr.
   */
  @Override
  public com.google.protobuf.ByteString
      getPcrBytes() {
    Object ref = pcr_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      pcr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SBS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object sbs_ = "";
  /**
   * <code>string sbs = 5;</code>
   * @return The sbs.
   */
  @Override
  public String getSbs() {
    Object ref = sbs_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sbs_ = s;
      return s;
    }
  }
  /**
   * <code>string sbs = 5;</code>
   * @return The bytes for sbs.
   */
  @Override
  public com.google.protobuf.ByteString
      getSbsBytes() {
    Object ref = sbs_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sbs_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, customerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(moodys_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, moodys_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pcr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, pcr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sbs_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sbs_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, customerId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(moodys_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, moodys_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pcr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, pcr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sbs_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sbs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof EvaluationResponse)) {
      return super.equals(obj);
    }
    EvaluationResponse other = (EvaluationResponse) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getCustomerId()
        .equals(other.getCustomerId())) return false;
    if (!getMoodys()
        .equals(other.getMoodys())) return false;
    if (!getPcr()
        .equals(other.getPcr())) return false;
    if (!getSbs()
        .equals(other.getSbs())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CUSTOMER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCustomerId().hashCode();
    hash = (37 * hash) + MOODYS_FIELD_NUMBER;
    hash = (53 * hash) + getMoodys().hashCode();
    hash = (37 * hash) + PCR_FIELD_NUMBER;
    hash = (53 * hash) + getPcr().hashCode();
    hash = (37 * hash) + SBS_FIELD_NUMBER;
    hash = (53 * hash) + getSbs().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static EvaluationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EvaluationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EvaluationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EvaluationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EvaluationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EvaluationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EvaluationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EvaluationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static EvaluationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static EvaluationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static EvaluationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EvaluationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(EvaluationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EvaluationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EvaluationResponse)
      EvaluationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RiskServiceOuterClass.internal_static_EvaluationResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RiskServiceOuterClass.internal_static_EvaluationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EvaluationResponse.class, Builder.class);
    }

    // Construct using net.csonic.grpc.server.EvaluationResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      customerId_ = "";
      moodys_ = "";
      pcr_ = "";
      sbs_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RiskServiceOuterClass.internal_static_EvaluationResponse_descriptor;
    }

    @Override
    public EvaluationResponse getDefaultInstanceForType() {
      return EvaluationResponse.getDefaultInstance();
    }

    @Override
    public EvaluationResponse build() {
      EvaluationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public EvaluationResponse buildPartial() {
      EvaluationResponse result = new EvaluationResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(EvaluationResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.customerId_ = customerId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.moodys_ = moodys_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.pcr_ = pcr_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sbs_ = sbs_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof EvaluationResponse) {
        return mergeFrom((EvaluationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(EvaluationResponse other) {
      if (other == EvaluationResponse.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getCustomerId().isEmpty()) {
        customerId_ = other.customerId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getMoodys().isEmpty()) {
        moodys_ = other.moodys_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getPcr().isEmpty()) {
        pcr_ = other.pcr_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getSbs().isEmpty()) {
        sbs_ = other.sbs_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              customerId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              moodys_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              pcr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              sbs_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public String getId() {
      Object ref = id_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object customerId_ = "";
    /**
     * <code>string customer_id = 2;</code>
     * @return The customerId.
     */
    public String getCustomerId() {
      Object ref = customerId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        customerId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string customer_id = 2;</code>
     * @return The bytes for customerId.
     */
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      Object ref = customerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customer_id = 2;</code>
     * @param value The customerId to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      customerId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string customer_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerId() {
      customerId_ = getDefaultInstance().getCustomerId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string customer_id = 2;</code>
     * @param value The bytes for customerId to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      customerId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object moodys_ = "";
    /**
     * <code>string moodys = 3;</code>
     * @return The moodys.
     */
    public String getMoodys() {
      Object ref = moodys_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        moodys_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string moodys = 3;</code>
     * @return The bytes for moodys.
     */
    public com.google.protobuf.ByteString
        getMoodysBytes() {
      Object ref = moodys_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        moodys_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string moodys = 3;</code>
     * @param value The moodys to set.
     * @return This builder for chaining.
     */
    public Builder setMoodys(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      moodys_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string moodys = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoodys() {
      moodys_ = getDefaultInstance().getMoodys();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string moodys = 3;</code>
     * @param value The bytes for moodys to set.
     * @return This builder for chaining.
     */
    public Builder setMoodysBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      moodys_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private Object pcr_ = "";
    /**
     * <code>string pcr = 4;</code>
     * @return The pcr.
     */
    public String getPcr() {
      Object ref = pcr_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pcr_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string pcr = 4;</code>
     * @return The bytes for pcr.
     */
    public com.google.protobuf.ByteString
        getPcrBytes() {
      Object ref = pcr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pcr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pcr = 4;</code>
     * @param value The pcr to set.
     * @return This builder for chaining.
     */
    public Builder setPcr(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      pcr_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string pcr = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPcr() {
      pcr_ = getDefaultInstance().getPcr();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string pcr = 4;</code>
     * @param value The bytes for pcr to set.
     * @return This builder for chaining.
     */
    public Builder setPcrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pcr_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private Object sbs_ = "";
    /**
     * <code>string sbs = 5;</code>
     * @return The sbs.
     */
    public String getSbs() {
      Object ref = sbs_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sbs_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sbs = 5;</code>
     * @return The bytes for sbs.
     */
    public com.google.protobuf.ByteString
        getSbsBytes() {
      Object ref = sbs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sbs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sbs = 5;</code>
     * @param value The sbs to set.
     * @return This builder for chaining.
     */
    public Builder setSbs(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      sbs_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string sbs = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSbs() {
      sbs_ = getDefaultInstance().getSbs();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string sbs = 5;</code>
     * @param value The bytes for sbs to set.
     * @return This builder for chaining.
     */
    public Builder setSbsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sbs_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EvaluationResponse)
  }

  // @@protoc_insertion_point(class_scope:EvaluationResponse)
  private static final EvaluationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new EvaluationResponse();
  }

  public static EvaluationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EvaluationResponse>
      PARSER = new com.google.protobuf.AbstractParser<EvaluationResponse>() {
    @Override
    public EvaluationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EvaluationResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<EvaluationResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public EvaluationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

