// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk-service.proto

package net.csonic.grpc.server;

public interface EvaluationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EvaluationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string customer_id = 1;</code>
   * @return The customerId.
   */
  String getCustomerId();
  /**
   * <code>string customer_id = 1;</code>
   * @return The bytes for customerId.
   */
  com.google.protobuf.ByteString
      getCustomerIdBytes();
}
