// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk-service.proto

package net.csonic.grpc.server;

public final class RiskServiceOuterClass {
  private RiskServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EvaluationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EvaluationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EvaluationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EvaluationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022risk-service.proto\"(\n\021EvaluationReques" +
      "t\022\023\n\013customer_id\030\001 \001(\t\"_\n\022EvaluationResp" +
      "onse\022\n\n\002id\030\001 \001(\t\022\023\n\013customer_id\030\002 \001(\t\022\016\n" +
      "\006moodys\030\003 \001(\t\022\013\n\003pcr\030\004 \001(\t\022\013\n\003sbs\030\005 \001(\t2" +
      "G\n\013RiskService\0228\n\rgetEvaluation\022\022.Evalua" +
      "tionRequest\032\023.EvaluationResponseB\032\n\026net." +
      "csonic.grpc.serverP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EvaluationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EvaluationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EvaluationRequest_descriptor,
        new String[] { "CustomerId", });
    internal_static_EvaluationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EvaluationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EvaluationResponse_descriptor,
        new String[] { "Id", "CustomerId", "Moodys", "Pcr", "Sbs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
