
microservices.customers:
  url: ${MSCUSTOMERS_URL:http://localhost:9060/}


dgs:
  graphql:
    schema-location:
      - "classpath*:schema/**/*.graphql*"
      - "classpath*:schema/**/*.gql"

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
  main:
    banner-mode: OFF
  datasource:
    #url: ${DB_URL:jdbc:mysql://svc-6c30b476-90da-4548-937b-57846a82fab7-dml.azr-virginia1-2.svc.singlestore.com:3306/dbCustomers}
    url: ${DB_URL:jdbc:singlestore://svc-6c30b476-90da-4548-937b-57846a82fab7-dml.azr-virginia1-2.svc.singlestore.com:3306/dbCustomers?pool=true&maxPoolSize=10}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:pwd}
    driver-class-name: com.singlestore.jdbc.Driver
  jpa:
    hibernate:
        ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

